import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { FormContextProvider } from "@/contexts/FormContext";
import { Providers } from "@/features/rtk/provider";
import FreelancerLayout from "@/layout/freelancer/FreelancerLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <FormContextProvider>
        <html lang="en">
          <body className={inter.className}>
            <FreelancerLayout>{children}</FreelancerLayout>
          </body>
        </html>
      </FormContextProvider>
    </Providers>
  );
}
