import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import FreelancerLayout from "@/layout/freelancer/FreelancerLayout";
import { Provider } from "react-redux";
import { store } from "@/features/store/store";
import { Providers } from "@/features/rtk/provider";
import { FormContextProvider } from "@/contexts/FormContext";
import ClientLayout from "@/layout/client/ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <FormContextProvider>
        <html lang="en">
          <body className={inter.className}>
            Client Layout.
            <ClientLayout>{children}</ClientLayout>
          </body>
        </html>
      </FormContextProvider>
    </Providers>
  );
}
